In [1]:
lst = [1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [5]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)
print(array.shape)
print(array.dtype)

[1 2 3 4]
(4,)
int32


In [7]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])

b=np.array([[10,20,30],[40,50,60]])
c=np.array(a+b)
print(c)
c.reshape(3,2)

[[11 22 33]
 [44 55 66]]


array([[11, 22],
       [33, 44],
       [55, 66]])

In [8]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [9]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [16]:
a1=np.random.normal(1,0.5,10)
print(a1)

[0.79449581 1.49213116 1.0072442  0.50120725 1.33831317 0.32582161
 0.19219034 1.35416919 1.6177969  0.30427025]


In [39]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.array([7,8,10])
print(np.diagonal((a1,a2,a3)))
print(np.trace((a1,a2,a3)))

[ 1  5 10]
16


In [73]:
import numpy as np
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a[0:1])

[[1 2 3]]


In [47]:
import numpy as np
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [48]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [49]:
np.arange(1,2048,564)
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [51]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column :",a1[:,1])

slicing column : [2 5]


In [52]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column :",a1[:,2])

slicing column : [3 6]


In [53]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row :",a1[0])

first row : [1 2 3]


In [54]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row :",a1[1])

second row : [4 5 6]


In [55]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [74]:
a1=np.random.normal(5,1,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median Value=",np.median(a1))

[5.92612607 4.72067446 4.82277472 4.1552783  4.86184741 4.12140768
 6.11584809 4.08692598 3.16340974 5.1121385 ]
Min value= 3.163409738769059
Max value= 6.115848091496011
Mean value= 4.708643096137783
Median Value= 4.7717245913665565


In [76]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.dot(a1,a2))

32


In [80]:
a1=np.array(([1,2],[3,4]))
a2=np.array(([5,6],[6,7]))
print(np.dot(a1,a2))

[[17 20]
 [39 46]]


In [87]:
import numpy as np
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a[0:3,0])

[1 4 7]


In [2]:
import pandas as pd
dict={"Name":["Chiikar","Surya","Mohit","Guddu"],
      "Email ID":["chiikar@mabbu.com","Surya@Great.com","Mohit@gangleader.com","Guddu@sate.com"],
      "Mobile Number":["12345678910","1235467098","6543217890","3467853643"],
      "Address":["Hyd","Hyd","Hyd","Hyd"]}
b=pd.DataFrame(dict)
print(b)

      Name              Email ID Mobile Number Address
0  Chiikar     chiikar@mabbu.com   12345678910     Hyd
1    Surya       Surya@Great.com    1235467098     Hyd
2    Mohit  Mohit@gangleader.com    6543217890     Hyd
3    Guddu        Guddu@sate.com    3467853643     Hyd
